// <auto-generated />
using System;
using CarbonFootprint.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CarbonFootprint.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CarbonFootprintDbContext))]
    [Migration("20260718091011_AddCalculationWarnings")]
    partial class AddCalculationWarnings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("app")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CarbonFootprint.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("users", "identity");
                });

            modelBuilder.Entity("CarbonFootprint.Infrastructure.Persistence.ActivityDataRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CanonicalUnitCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("canonical_unit_code");

                    b.Property<decimal>("CanonicalValue")
                        .HasPrecision(30, 12)
                        .HasColumnType("numeric(30,12)")
                        .HasColumnName("canonical_value");

                    b.Property<string>("ConversionRuleVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("conversion_rule_version");

                    b.Property<string>("EvidenceSha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("evidence_sha256");

                    b.Property<Guid>("FactorVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("factor_version_id");

                    b.Property<Guid>("InventoryProjectVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_project_version_id");

                    b.Property<int>("LifecycleStage")
                        .HasColumnType("integer")
                        .HasColumnName("lifecycle_stage");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date")
                        .HasColumnName("period_end");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date")
                        .HasColumnName("period_start");

                    b.Property<string>("RawUnitCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("raw_unit_code");

                    b.Property<decimal>("RawValue")
                        .HasPrecision(30, 12)
                        .HasColumnType("numeric(30,12)")
                        .HasColumnName("raw_value");

                    b.HasKey("Id")
                        .HasName("pk_activity_data_versions");

                    b.HasIndex("FactorVersionId")
                        .HasDatabaseName("ix_activity_data_versions_factor_version_id");

                    b.HasIndex("InventoryProjectVersionId")
                        .HasDatabaseName("ix_activity_data_versions_inventory_project_version_id");

                    b.ToTable("activity_data_versions", "app");
                });

            modelBuilder.Entity("CarbonFootprint.Infrastructure.Persistence.AuditEventRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("AfterHash")
                        .HasColumnType("text")
                        .HasColumnName("after_hash");

                    b.Property<string>("BeforeHash")
                        .HasColumnType("text")
                        .HasColumnName("before_hash");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("resource_type");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id")
                        .HasName("pk_audit_events");

                    b.HasIndex("OrganizationId", "Timestamp")
                        .HasDatabaseName("ix_audit_events_organization_id_timestamp");

                    b.ToTable("audit_events", "app");
                });

            modelBuilder.Entity("CarbonFootprint.Infrastructure.Persistence.CalculationLineRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid")
                        .HasColumnName("activity_id");

                    b.Property<string>("ActivityUnitCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("activity_unit_code");

                    b.Property<Guid>("CalculationRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("calculation_run_id");

                    b.Property<decimal>("CanonicalActivityValue")
                        .HasPrecision(30, 12)
                        .HasColumnType("numeric(30,12)")
                        .HasColumnName("canonical_activity_value");

                    b.Property<decimal>("Emissions")
                        .HasPrecision(38, 15)
                        .HasColumnType("numeric(38,15)")
                        .HasColumnName("emissions");

                    b.Property<string>("EmissionsUnitCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("emissions_unit_code");

                    b.Property<string>("FactorUnit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("factor_unit");

                    b.Property<decimal>("FactorValue")
                        .HasPrecision(30, 15)
                        .HasColumnType("numeric(30,15)")
                        .HasColumnName("factor_value");

                    b.Property<Guid>("FactorVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("factor_version_id");

                    b.Property<string>("FormulaId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("formula_id");

                    b.Property<int>("LifecycleStage")
                        .HasColumnType("integer")
                        .HasColumnName("lifecycle_stage");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.HasKey("Id")
                        .HasName("pk_calculation_line_items");

                    b.HasIndex("CalculationRunId")
                        .HasDatabaseName("ix_calculation_line_items_calculation_run_id");

                    b.ToTable("calculation_line_items", "app");
                });

            modelBuilder.Entity("CarbonFootprint.Infrastructure.Persistence.CalculationRunRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CanonicalInputManifest")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("canonical_input_manifest");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EngineBuild")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("engine_build");

                    b.Property<string>("GwpVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gwp_version");

                    b.Property<string>("InputSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("input_sha256");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("PcrVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pcr_version");

                    b.Property<decimal>("ProductTotal")
                        .HasPrecision(38, 15)
                        .HasColumnType("numeric(38,15)")
                        .HasColumnName("product_total");

                    b.Property<Guid>("ProjectVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_version_id");

                    b.Property<string>("RuleSetVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rule_set_version");

                    b.Property<Guid?>("SupersedesRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("supersedes_run_id");

                    b.Property<string>("UnitCatalogueVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit_catalogue_version");

                    b.HasKey("Id")
                        .HasName("pk_calculation_runs");

                    b.HasIndex("ProjectVersionId")
                        .HasDatabaseName("ix_calculation_runs_project_version_id");

                    b.HasIndex("SupersedesRunId")
                        .HasDatabaseName("ix_calculation_runs_supersedes_run_id");

                    b.HasIndex("OrganizationId", "InputSha256")
                        .HasDatabaseName("ix_calculation_runs_organization_id_input_sha256");

                    b.ToTable("calculation_runs", "app");
                });

            modelBuilder.Entity("CarbonFootprint.Infrastructure.Persistence.CalculationStageSummaryRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CalculationRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("calculation_run_id");

                    b.Property<decimal>("Emissions")
                        .HasPrecision(38, 15)
                        .HasColumnType("numeric(38,15)")
                        .HasColumnName("emissions");

                    b.Property<int>("LifecycleStage")
                        .HasColumnType("integer")
                        .HasColumnName("lifecycle_stage");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.HasKey("Id")
                        .HasName("pk_calculation_stage_summaries");

                    b.HasIndex("CalculationRunId", "LifecycleStage")
                        .IsUnique()
                        .HasDatabaseName("ix_calculation_stage_summaries_calculation_run_id_lifecycle_st");

                    b.ToTable("calculation_stage_summaries", "app");
                });

            modelBuilder.Entity("CarbonFootprint.Infrastructure.Persistence.CalculationWarningRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CalculationRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("calculation_run_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("message");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.HasKey("Id")
                        .HasName("pk_calculation_warnings");

                    b.HasIndex("CalculationRunId")
                        .HasDatabaseName("ix_calculation_warnings_calculation_run_id");

                    b.ToTable("calculation_warnings", "app");
                });

            modelBuilder.Entity("CarbonFootprint.Infrastructure.Persistence.EmissionFactorVersionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DenominatorUnitCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("denominator_unit_code");

                    b.Property<Guid>("FactorId")
                        .HasColumnType("uuid")
                        .HasColumnName("factor_id");

                    b.Property<string>("Geography")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("geography");

                    b.Property<string>("LicenseCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("license_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<string>("NumeratorUnitCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numerator_unit_code");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("PublicationStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("publication_status");

                    b.Property<string>("SourceDatasetVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_dataset_version");

                    b.Property<Guid?>("SupersedesVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("supersedes_version_id");

                    b.Property<DateOnly?>("ValidFrom")
                        .HasColumnType("date")
                        .HasColumnName("valid_from");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date")
                        .HasColumnName("valid_to");

                    b.Property<decimal>("Value")
                        .HasPrecision(30, 15)
                        .HasColumnType("numeric(30,15)")
                        .HasColumnName("value");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id")
                        .HasName("pk_emission_factor_versions");

                    b.HasIndex("SupersedesVersionId")
                        .HasDatabaseName("ix_emission_factor_versions_supersedes_version_id");

                    b.HasIndex("FactorId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_emission_factor_versions_factor_id_version_number");

                    b.ToTable("emission_factor_versions", "app");
                });

            modelBuilder.Entity("CarbonFootprint.Infrastructure.Persistence.EvidenceFileRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActivityDataId")
                        .HasColumnType("uuid")
                        .HasColumnName("activity_data_id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("object_key");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("original_file_name");

                    b.Property<string>("ScanStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("scan_status");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sha256");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.HasKey("Id")
                        .HasName("pk_evidence_files");

                    b.HasIndex("ActivityDataId")
                        .HasDatabaseName("ix_evidence_files_activity_data_id");

                    b.HasIndex("OrganizationId", "Sha256")
                        .HasDatabaseName("ix_evidence_files_organization_id_sha256");

                    b.ToTable("evidence_files", "app");
                });

            modelBuilder.Entity("CarbonFootprint.Infrastructure.Persistence.InventoryProjectVersionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FunctionalUnit")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("functional_unit");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("PcrVersion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("pcr_version");

                    b.Property<Guid?>("PcrVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("pcr_version_id");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date")
                        .HasColumnName("period_end");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date")
                        .HasColumnName("period_start");

                    b.Property<Guid>("ProductVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_version_id");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.Property<string>("WorkflowStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("workflow_status");

                    b.HasKey("Id")
                        .HasName("pk_inventory_project_versions");

                    b.HasIndex("PcrVersionId")
                        .HasDatabaseName("ix_inventory_project_versions_pcr_version_id");

                    b.HasIndex("ProductVersionId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_inventory_project_versions_product_version_id_version_number");

                    b.ToTable("inventory_project_versions", "app");
                });

            modelBuilder.Entity("CarbonFootprint.Infrastructure.Persistence.OrganizationMembershipRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_organization_memberships");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_organization_memberships_user_id");

                    b.HasIndex("OrganizationId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_organization_memberships_organization_id_user_id");

                    b.ToTable("organization_memberships", "app");
                });

            modelBuilder.Entity("CarbonFootprint.Infrastructure.Persistence.OrganizationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_organizations");

                    b.ToTable("organizations", "app");
                });

            modelBuilder.Entity("CarbonFootprint.Infrastructure.Persistence.PcrVersionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("PublicationStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("publication_status");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("registration_number");

                    b.Property<string>("SourceReference")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("source_reference");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<DateOnly?>("ValidFrom")
                        .HasColumnType("date")
                        .HasColumnName("valid_from");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date")
                        .HasColumnName("valid_to");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.Property<DateTimeOffset?>("WithdrawnAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("withdrawn_at");

                    b.HasKey("Id")
                        .HasName("pk_pcr_versions");

                    b.HasIndex("OrganizationId", "RegistrationNumber", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_pcr_versions_organization_id_registration_number_version_nu");

                    b.ToTable("pcr_versions", "app");
                });

            modelBuilder.Entity("CarbonFootprint.Infrastructure.Persistence.ProductRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_products_organization_id");

                    b.ToTable("products", "app");
                });

            modelBuilder.Entity("CarbonFootprint.Infrastructure.Persistence.ProductVersionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("NameZhTw")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name_zh_tw");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id")
                        .HasName("pk_product_versions");

                    b.HasIndex("ProductId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_product_versions_product_id_version_number");

                    b.ToTable("product_versions", "app");
                });

            modelBuilder.Entity("CarbonFootprint.Infrastructure.Persistence.UnitRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CanonicalCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("canonical_code");

                    b.Property<string>("CatalogueVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("catalogue_version");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Dimension")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dimension");

                    b.Property<decimal>("OffsetToCanonical")
                        .HasPrecision(30, 15)
                        .HasColumnType("numeric(30,15)")
                        .HasColumnName("offset_to_canonical");

                    b.Property<decimal>("ScaleToCanonical")
                        .HasPrecision(30, 15)
                        .HasColumnType("numeric(30,15)")
                        .HasColumnName("scale_to_canonical");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("symbol");

                    b.HasKey("Id")
                        .HasName("pk_units");

                    b.HasIndex("Code", "CatalogueVersion")
                        .IsUnique()
                        .HasDatabaseName("ix_units_code_catalogue_version");

                    b.ToTable("units", "app");

                    b.HasData(
                        new
                        {
                            Id = new Guid("71000000-0000-0000-0000-000000000001"),
                            CanonicalCode = "kg",
                            CatalogueVersion = "units-p0-v1",
                            Code = "kg",
                            Dimension = "mass",
                            OffsetToCanonical = 0m,
                            ScaleToCanonical = 1m,
                            Symbol = "kg"
                        },
                        new
                        {
                            Id = new Guid("71000000-0000-0000-0000-000000000002"),
                            CanonicalCode = "kg",
                            CatalogueVersion = "units-p0-v1",
                            Code = "g",
                            Dimension = "mass",
                            OffsetToCanonical = 0m,
                            ScaleToCanonical = 0.001m,
                            Symbol = "g"
                        },
                        new
                        {
                            Id = new Guid("71000000-0000-0000-0000-000000000003"),
                            CanonicalCode = "kWh",
                            CatalogueVersion = "units-p0-v1",
                            Code = "kWh",
                            Dimension = "energy",
                            OffsetToCanonical = 0m,
                            ScaleToCanonical = 1m,
                            Symbol = "kWh"
                        },
                        new
                        {
                            Id = new Guid("71000000-0000-0000-0000-000000000004"),
                            CanonicalCode = "tonne-km",
                            CatalogueVersion = "units-p0-v1",
                            Code = "tonne-km",
                            Dimension = "transport-work",
                            OffsetToCanonical = 0m,
                            ScaleToCanonical = 1m,
                            Symbol = "t·km"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("roles", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_role_claims_role_id");

                    b.ToTable("role_claims", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_claims_user_id");

                    b.ToTable("user_claims", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_logins_user_id");

                    b.ToTable("user_logins", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.ToTable("user_roles", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_user_tokens");

                    b.ToTable("user_tokens", "identity");
                });

            modelBuilder.Entity("CarbonFootprint.Infrastructure.Persistence.ActivityDataRecord", b =>
                {
                    b.HasOne("CarbonFootprint.Infrastructure.Persistence.EmissionFactorVersionRecord", null)
                        .WithMany()
                        .HasForeignKey("FactorVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_activity_data_versions_emission_factor_versions_factor_vers");

                    b.HasOne("CarbonFootprint.Infrastructure.Persistence.InventoryProjectVersionRecord", null)
                        .WithMany()
                        .HasForeignKey("InventoryProjectVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_activity_data_versions_inventory_project_versions_inventory");
                });

            modelBuilder.Entity("CarbonFootprint.Infrastructure.Persistence.CalculationLineRecord", b =>
                {
                    b.HasOne("CarbonFootprint.Infrastructure.Persistence.CalculationRunRecord", null)
                        .WithMany()
                        .HasForeignKey("CalculationRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_calculation_line_items_calculation_runs_calculation_run_id");
                });

            modelBuilder.Entity("CarbonFootprint.Infrastructure.Persistence.CalculationRunRecord", b =>
                {
                    b.HasOne("CarbonFootprint.Infrastructure.Persistence.InventoryProjectVersionRecord", null)
                        .WithMany()
                        .HasForeignKey("ProjectVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_calculation_runs_inventory_project_versions_project_version");

                    b.HasOne("CarbonFootprint.Infrastructure.Persistence.CalculationRunRecord", null)
                        .WithMany()
                        .HasForeignKey("SupersedesRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_calculation_runs_calculation_runs_supersedes_run_id");
                });

            modelBuilder.Entity("CarbonFootprint.Infrastructure.Persistence.CalculationStageSummaryRecord", b =>
                {
                    b.HasOne("CarbonFootprint.Infrastructure.Persistence.CalculationRunRecord", null)
                        .WithMany()
                        .HasForeignKey("CalculationRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_calculation_stage_summaries_calculation_runs_calculation_ru");
                });

            modelBuilder.Entity("CarbonFootprint.Infrastructure.Persistence.CalculationWarningRecord", b =>
                {
                    b.HasOne("CarbonFootprint.Infrastructure.Persistence.CalculationRunRecord", null)
                        .WithMany()
                        .HasForeignKey("CalculationRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_calculation_warnings_calculation_runs_calculation_run_id");
                });

            modelBuilder.Entity("CarbonFootprint.Infrastructure.Persistence.EmissionFactorVersionRecord", b =>
                {
                    b.HasOne("CarbonFootprint.Infrastructure.Persistence.EmissionFactorVersionRecord", null)
                        .WithMany()
                        .HasForeignKey("SupersedesVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_emission_factor_versions_emission_factor_versions_supersede");
                });

            modelBuilder.Entity("CarbonFootprint.Infrastructure.Persistence.EvidenceFileRecord", b =>
                {
                    b.HasOne("CarbonFootprint.Infrastructure.Persistence.ActivityDataRecord", null)
                        .WithMany()
                        .HasForeignKey("ActivityDataId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_evidence_files_activity_data_versions_activity_data_id");
                });

            modelBuilder.Entity("CarbonFootprint.Infrastructure.Persistence.InventoryProjectVersionRecord", b =>
                {
                    b.HasOne("CarbonFootprint.Infrastructure.Persistence.PcrVersionRecord", null)
                        .WithMany()
                        .HasForeignKey("PcrVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_inventory_project_versions_pcr_versions_pcr_version_id");

                    b.HasOne("CarbonFootprint.Infrastructure.Persistence.ProductVersionRecord", null)
                        .WithMany()
                        .HasForeignKey("ProductVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_project_versions_product_versions_product_version");
                });

            modelBuilder.Entity("CarbonFootprint.Infrastructure.Persistence.OrganizationMembershipRecord", b =>
                {
                    b.HasOne("CarbonFootprint.Infrastructure.Persistence.OrganizationRecord", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_organization_memberships_organizations_organization_id");

                    b.HasOne("CarbonFootprint.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_organization_memberships_users_user_id");
                });

            modelBuilder.Entity("CarbonFootprint.Infrastructure.Persistence.ProductRecord", b =>
                {
                    b.HasOne("CarbonFootprint.Infrastructure.Persistence.OrganizationRecord", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_products_organizations_organization_id");
                });

            modelBuilder.Entity("CarbonFootprint.Infrastructure.Persistence.ProductVersionRecord", b =>
                {
                    b.HasOne("CarbonFootprint.Infrastructure.Persistence.ProductRecord", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_product_versions_products_product_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_claims_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("CarbonFootprint.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_claims_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("CarbonFootprint.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_logins_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("CarbonFootprint.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("CarbonFootprint.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_tokens_users_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
